export type DemoCategory = 'microsoft' | 'github' | 'claude' | 'open-source' | 'custom';

export interface DemoRepository {
  category: DemoCategory;
  owner: string;
  repo: string;
  url: string;
}

function repo(category: DemoCategory, owner: string, name: string): DemoRepository {
  return {
    category,
    owner,
    repo: name,
    url: `https://github.com/${owner}/${name}`,
  };
}

export const DEFAULT_DEMO_REPOSITORIES: DemoRepository[] = [
  repo('microsoft', 'microsoft', 'vscode'),
  repo('microsoft', 'microsoft', 'TypeScript'),
  repo('microsoft', 'microsoft', 'playwright'),
  repo('microsoft', 'microsoft', 'terminal'),
  repo('microsoft', 'microsoft', 'PowerToys'),
  repo('microsoft', 'microsoft', 'winget-cli'),
  repo('microsoft', 'microsoft', 'semantic-kernel'),
  repo('microsoft', 'microsoft', 'autogen'),
  repo('microsoft', 'microsoft', 'kiota'),
  repo('microsoft', 'microsoft', 'fluentui'),
  repo('microsoft', 'microsoft', 'fast'),
  repo('microsoft', 'microsoft', 'monaco-editor'),
  repo('microsoft', 'microsoft', 'onnxruntime'),
  repo('microsoft', 'microsoft', 'DeepSpeed'),
  repo('microsoft', 'microsoft', 'Web-Dev-For-Beginners'),
  repo('microsoft', 'microsoft', 'AI-For-Beginners'),
  repo('microsoft', 'microsoft', 'AdaptiveCards'),
  repo('microsoft', 'microsoft', 'BotBuilder-Samples'),
  repo('microsoft', 'microsoft', 'teams-ai'),
  repo('microsoft', 'microsoft', 'devhome'),
  repo('microsoft', 'microsoft', 'WSL'),
  repo('microsoft', 'Azure', 'azure-sdk-for-js'),
  repo('microsoft', 'Azure', 'azure-sdk-for-python'),
  repo('microsoft', 'Azure', 'azure-rest-api-specs'),
  repo('microsoft', 'Azure-Samples', 'octocat-supply'),

  repo('github', 'github', 'docs'),
  repo('github', 'github', 'github-mcp-server'),
  repo('github', 'github', 'codespaces-jupyter'),
  repo('github', 'github', 'codeql'),
  repo('github', 'github', 'super-linter'),
  repo('github', 'github', 'linguist'),
  repo('github', 'github', 'hub'),
  repo('github', 'github', 'gh-ost'),
  repo('github', 'github', 'gitignore'),
  repo('github', 'github', 'awesome-copilot'),
  repo('github', 'github', 'actions-migrations-via-copilot'),
  repo('github', 'github', 'copilot-docs'),
  repo('github', 'github', 'semantic'),
  repo('github', 'actions', 'runner'),
  repo('github', 'actions', 'toolkit'),
  repo('github', 'actions', 'checkout'),
  repo('github', 'actions', 'setup-node'),
  repo('github', 'actions', 'upload-artifact'),
  repo('github', 'actions', 'starter-workflows'),
  repo('github', 'cli', 'cli'),
  repo('github', 'dependabot', 'dependabot-core'),
  repo('github', 'octokit', 'core.js'),
  repo('github', 'octokit', 'graphql.js'),
  repo('github', 'octokit', 'rest.js'),
  repo('github', 'primer', 'react'),

  repo('claude', 'anthropics', 'anthropic-cookbook'),
  repo('claude', 'anthropics', 'courses'),
  repo('claude', 'anthropics', 'claude-code-action'),
  repo('claude', 'anthropics', 'claude-code-base-action'),
  repo('claude', 'anthropics', 'claude-code-sdk-python'),
  repo('claude', 'anthropics', 'claude-agent-sdk-typescript'),
  repo('claude', 'anthropics', 'claude-agent-sdk-python'),
  repo('claude', 'anthropics', 'anthropic-sdk-php'),
  repo('claude', 'anthropics', 'anthropic-sdk-typescript'),
  repo('claude', 'anthropics', 'anthropic-sdk-python'),
  repo('claude', 'anthropics', 'anthropic-sdk-go'),
  repo('claude', 'anthropics', 'anthropic-sdk-java'),
  repo('claude', 'anthropics', 'anthropic-sdk-csharp'),
  repo('claude', 'anthropics', 'anthropic-sdk-ruby'),
  repo('claude', 'anthropics', 'anthropic-quickstarts'),
  repo('claude', 'anthropics', 'anthropic-tools'),
  repo('claude', 'anthropics', 'claude-code'),
  repo('claude', 'modelcontextprotocol', 'servers'),
  repo('claude', 'modelcontextprotocol', 'typescript-sdk'),
  repo('claude', 'modelcontextprotocol', 'python-sdk'),
  repo('claude', 'modelcontextprotocol', 'inspector'),
  repo('claude', 'modelcontextprotocol', 'registry'),
  repo('claude', 'modelcontextprotocol', 'create-python-server'),
  repo('claude', 'modelcontextprotocol', 'create-typescript-server'),
  repo('claude', 'modelcontextprotocol', 'docs'),

  repo('open-source', 'vercel', 'next.js'),
  repo('open-source', 'facebook', 'react'),
  repo('open-source', 'vuejs', 'core'),
  repo('open-source', 'sveltejs', 'svelte'),
  repo('open-source', 'vitejs', 'vite'),
  repo('open-source', 'nodejs', 'node'),
  repo('open-source', 'denoland', 'deno'),
  repo('open-source', 'rust-lang', 'rust'),
  repo('open-source', 'golang', 'go'),
  repo('open-source', 'python', 'cpython'),
  repo('open-source', 'kubernetes', 'kubernetes'),
  repo('open-source', 'docker', 'cli'),
  repo('open-source', 'moby', 'moby'),
  repo('open-source', 'hashicorp', 'terraform'),
  repo('open-source', 'ansible', 'ansible'),
  repo('open-source', 'elastic', 'kibana'),
  repo('open-source', 'grafana', 'grafana'),
  repo('open-source', 'prometheus', 'prometheus'),
  repo('open-source', 'apache', 'airflow'),
  repo('open-source', 'apache', 'spark'),
  repo('open-source', 'pytorch', 'pytorch'),
  repo('open-source', 'tensorflow', 'tensorflow'),
  repo('open-source', 'huggingface', 'transformers'),
  repo('open-source', 'langchain-ai', 'langchain'),
  repo('open-source', 'openai', 'openai-python'),
];
